version: '3.8'
services:
  frontend:
    image: ushankamesh33/medifind-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: ushankamesh33/medifind-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MYSQL_ROOT_PASSWORD=@Kamesh9396164
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - ./backend:/app  # For dev hot-reload

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "@Kamesh9396164"
      MYSQL_DATABASE: healthdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pYourPassword" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql-data:
